chore: update request types supported by webhook channel
knocklabs/docs pull request #671
Opened 2024-11-19 02:43 UTC by rachael-t

### Description

Updates the request types supported by the webhook channel to align with what is available/supported in the dashboard.

### Screenshots

<img width="564" alt="Screenshot 2024-11-18 at 7 38 33 PM" src="https://github.com/user-attachments/assets/f1a53c15-32bc-45cd-9a65-f5f150af8026">

2024-11-19 17:38 UTC, cellomatt commented on content/integrations/webhook/overview.mdx
> +You can use the Knock webhook channel type to build a custom channel that sends a webhook request to a configured endpoint. This endpoint can be static, or can be dynamically built using liquid varia
<img width="885" alt="image" src="https://github.com/user-attachments/assets/66b8e903-48d4-48b8-9261-d123f139220e">

2024-11-19 17:40 UTC, cellomatt commented on content/integrations/webhook/overview.mdx
> +You can use the Knock webhook channel type to build a custom channel that sends a webhook request to a configured endpoint. This endpoint can be static, or can be dynamically built using liquid varia
Wherever we land on this, I think we should also make updates to https://docs.knock.app/designing-workflows/fetch-function to make sure it includes all the available HTTP methods and that styling is consistent across these two pages for the `code` style (colored or not)

2024-11-19 17:45 UTC, cellomatt requested changes
We should also make updates to https://docs.knock.app/designing-workflows/fetch-function to make sure it includes all the available HTTP methods and that styling is consistent across these two pages for the `code` style (colored or not)

2024-11-27 20:12 UTC, rachael-t commented on content/integrations/webhook/overview.mdx
> +You can use the Knock webhook channel type to build a custom channel that sends a webhook request to a configured endpoint. This endpoint can be static, or can be dynamically built using liquid varia
I love this actually. Thank you for thinking of this! 🙌

2024-12-02 21:26 UTC, cellomatt approved these changes
just one tiny nit. thanks for making this update!!

2024-12-02 21:26 UTC, cellomatt commented on content/designing-workflows/fetch-function.mdx
> +- **Request method** - You can select one of <span className="text-xs font-medium text-gray-600 dark:text-gray-300 border border-transparent font-mono rounded p-1 center bg-blue-100 dark:bg-transpare
```suggestion
- **Request method** - You can select one of <span className="text-xs font-medium text-gray-600 dark:text-gray-300 border border-transparent font-mono rounded p-1 center bg-blue-100 dark:bg-transparent dark:border-blue-600">GET</span> (default), <span className="text-xs font-medium text-gray-600 dark:text-gray-300 border border-transparent font-mono rounded p-1 center bg-green-100 dark:bg-transparent dark:border-green-600">POST</span>, <span className="text-xs font-medium text-gray-600 dark:text-gray-300 border border-transparent font-mono rounded p-1 center bg-yellow-100 dark:bg-transparent dark:border-yellow-500">PUT</span>, <span className="text-xs font-medium text-gray-600 dark:text-gray-300 border border-transparent font-mono rounded p-1 center bg-red-100 dark:bg-transparent dark:border-red-500">DELETE</span>, or <span className="text-xs font-medium text-gray-600 dark:text-gray-300 border border-transparent font-mono rounded p-1 center bg-purple-100 dark:bg-transparent dark:border-purple-500">PATCH</span>.
```
nit, add commas after each request type

2024-12-03 23:39 UTC, merged